"""Writes scripts/backfill/pupdojo-legal.json, the translated legal payload for Pupdojo.

Run: python3 scripts/backfill/pupdojo-legal.py
Facts it relies on (from the app itself): no account, no backend, data stored on the device
and in the user's private iCloud (CloudKit) database, optional photos, local notifications,
on-device analytics only, subscriptions through the App Store and RevenueCat, no AI, no ads.
"""
import json
import os

UPDATED = "2026-10-01"
SUPPORT = "support@scriptiastories.com"
PRIVACY = "privacy@scriptiastories.com"
SECURITY = "security@scriptiastories.com"
LEGAL = "legal@scriptiastories.com"


def sec(id_, title, en, es, ca):
    return {"id": id_, "title": dict(zip(("en", "es", "ca"), title)), "body": {"en": en, "es": es, "ca": ca}}


def doc(key, slug, title, description, sections, label=None):
    d = {"docKey": key, "slug": slug, "lastUpdated": UPDATED,
         "title": dict(zip(("en", "es", "ca"), title)),
         "description": dict(zip(("en", "es", "ca"), description)),
         "sections": sections}
    if label:
        d["labelKey"] = label
    return d


privacy = doc("privacy", "privacy",
    ("Pupdojo Privacy Policy", "Política de privacidad de Pupdojo", "Política de privacitat de Pupdojo"),
    ("How Pupdojo, the dog training app, handles your information: what stays on your device, what syncs through your iCloud and what we never collect.",
     "Cómo trata tu información Pupdojo, la app de adiestramiento canino: qué se queda en tu dispositivo, qué se sincroniza con tu iCloud y qué no recogemos nunca.",
     "Com tracta la teva informació Pupdojo, l'app d'ensinistrament caní: què es queda al teu dispositiu, què se sincronitza amb el teu iCloud i què no recollim mai."),
    [
        sec("introduction", ("Introduction", "Introducción", "Introducció"),
            ["This Privacy Policy explains how Pupdojo, a dog training app developed by Idion, handles your information. It applies to the Pupdojo app for iPhone and iPad, not to other Idion products.",
             "Pupdojo is built so that we do not need your personal information: there is no account, no sign-in and no Pupdojo server that stores your training data."],
            ["Esta Política de privacidad explica cómo trata tu información Pupdojo, una app de adiestramiento canino desarrollada por Idion. Se aplica a la app Pupdojo para iPhone y iPad, no a otros productos de Idion.",
             "Pupdojo está diseñada para no necesitar tus datos personales: no hay cuenta, no hay inicio de sesión y no existe ningún servidor de Pupdojo que guarde tus datos de adiestramiento."],
            ["Aquesta Política de privacitat explica com tracta la teva informació Pupdojo, una app d'ensinistrament caní desenvolupada per Idion. S'aplica a l'app Pupdojo per a iPhone i iPad, no a altres productes d'Idion.",
             "Pupdojo està dissenyada per no necessitar les teves dades personals: no hi ha compte, no hi ha inici de sessió i no existeix cap servidor de Pupdojo que desi les teves dades d'ensinistrament."]),
        sec("informationYouEnter", ("Information you enter", "Información que introduces", "Informació que introdueixes"),
            ["To build a training plan, Pupdojo asks about your dog: name, age or birthday, breed, size, energy level, the habits you want to work on, your experience and your preferred session length and reminder time. You can also add photos of your dog, journal entries, potty and walk logs, and ratings of each exercise.",
             "This information is about your dog and your training. It is stored on your device and, if iCloud is turned on, in your private iCloud database. It is never sent to us."],
            ["Para crear un plan de adiestramiento, Pupdojo te pregunta por tu perro: nombre, edad o fecha de nacimiento, raza, tamaño, nivel de energía, los hábitos que quieres trabajar, tu experiencia y la duración de sesión y hora de recordatorio que prefieres. También puedes añadir fotos de tu perro, entradas de diario, registros de pipí y paseos, y valoraciones de cada ejercicio.",
             "Esta información trata sobre tu perro y tu adiestramiento. Se guarda en tu dispositivo y, si tienes iCloud activado, en tu base de datos privada de iCloud. Nunca nos llega a nosotros."],
            ["Per crear un pla d'ensinistrament, Pupdojo et pregunta pel teu gos: nom, edat o data de naixement, raça, mida, nivell d'energia, els hàbits que vols treballar, la teva experiència i la durada de sessió i hora de recordatori que prefereixes. També pots afegir fotos del teu gos, entrades de diari, registres de pipí i passejos, i valoracions de cada exercici.",
             "Aquesta informació tracta del teu gos i del teu ensinistrament. Es desa al teu dispositiu i, si tens l'iCloud activat, a la teva base de dades privada d'iCloud. Mai no ens arriba a nosaltres."]),
        sec("iCloudSync", ("iCloud sync", "Sincronización con iCloud", "Sincronització amb l'iCloud"),
            ["If you are signed in to iCloud, Pupdojo keeps your dogs, plans and progress in sync across your iPhone and iPad using Apple's CloudKit private database. That database belongs to your Apple Account: Apple stores it under its own privacy policy, and Idion cannot read it.",
             "You can turn iCloud sync off for Pupdojo at any time in your device's Settings. Your data then stays only on that device."],
            ["Si has iniciado sesión en iCloud, Pupdojo mantiene sincronizados tus perros, planes y progreso entre tu iPhone y tu iPad mediante la base de datos privada de CloudKit de Apple. Esa base de datos pertenece a tu cuenta de Apple: Apple la almacena según su propia política de privacidad, e Idion no puede leerla.",
             "Puedes desactivar la sincronización de iCloud para Pupdojo cuando quieras en los Ajustes del dispositivo. Entonces tus datos se quedan solo en ese dispositivo."],
            ["Si has iniciat sessió a l'iCloud, Pupdojo manté sincronitzats els teus gossos, plans i progrés entre el teu iPhone i el teu iPad mitjançant la base de dades privada de CloudKit d'Apple. Aquesta base de dades pertany al teu compte d'Apple: Apple l'emmagatzema segons la seva pròpia política de privacitat, i Idion no la pot llegir.",
             "Pots desactivar la sincronització de l'iCloud per a Pupdojo quan vulguis a la Configuració del dispositiu. Llavors les teves dades es queden només en aquell dispositiu."]),
        sec("permissions", ("Device permissions", "Permisos del dispositivo", "Permisos del dispositiu"),
            ["Camera and photos: only used when you choose to take or pick a photo of your dog. Notifications: only requested after you choose a reminder time, and scheduled on your device. Pupdojo does not use your location, contacts, microphone or health data."],
            ["Cámara y fotos: solo se usan cuando decides hacer o elegir una foto de tu perro. Notificaciones: solo se piden después de que elijas una hora de recordatorio, y se programan en tu dispositivo. Pupdojo no usa tu ubicación, contactos, micrófono ni datos de salud."],
            ["Càmera i fotos: només s'utilitzen quan decideixes fer o triar una foto del teu gos. Notificacions: només es demanen després que triïs una hora de recordatori, i es programen al teu dispositiu. Pupdojo no fa servir la teva ubicació, contactes, micròfon ni dades de salut."]),
        sec("doNotCollect", ("What we do not collect", "Lo que no recogemos", "El que no recollim"),
            ["We do not collect your name, email address, phone number, location or advertising identifier. Pupdojo has no ads, does not track you across other apps or websites, and does not sell or share personal information.",
             "Usage events that help us debug the app are written to your device's local log only and never leave your device."],
            ["No recogemos tu nombre, correo electrónico, teléfono, ubicación ni identificador de publicidad. Pupdojo no tiene anuncios, no te rastrea en otras apps o webs y no vende ni comparte información personal.",
             "Los eventos de uso que nos ayudan a depurar la app se escriben solo en el registro local de tu dispositivo y nunca salen de él."],
            ["No recollim el teu nom, correu electrònic, telèfon, ubicació ni identificador de publicitat. Pupdojo no té anuncis, no et rastreja en altres apps o webs i no ven ni comparteix informació personal.",
             "Els esdeveniments d'ús que ens ajuden a depurar l'app s'escriuen només al registre local del teu dispositiu i mai no en surten."]),
        sec("subscriptionsAndPayments", ("Subscriptions and payments", "Suscripciones y pagos", "Subscripcions i pagaments"),
            ["Pupdojo offers a paid plan, Pupdojo Pro. Payments are handled by Apple through the App Store; we never see your card or banking details.",
             "To know whether your Pro plan is active, Pupdojo uses RevenueCat, a subscription service. RevenueCat receives your App Store purchase history together with a random app user identifier that is not linked to your name or email. This is the only data that leaves your device, and it is used only to unlock the features you paid for and to restore them on your other devices."],
            ["Pupdojo ofrece un plan de pago, Pupdojo Pro. Los pagos los gestiona Apple a través del App Store; nunca vemos los datos de tu tarjeta ni bancarios.",
             "Para saber si tu plan Pro está activo, Pupdojo usa RevenueCat, un servicio de suscripciones. RevenueCat recibe tu historial de compras del App Store junto con un identificador aleatorio de usuario de la app que no está vinculado a tu nombre ni a tu correo. Es el único dato que sale de tu dispositivo, y solo se usa para desbloquear lo que has pagado y restaurarlo en tus otros dispositivos."],
            ["Pupdojo ofereix un pla de pagament, Pupdojo Pro. Els pagaments els gestiona Apple a través de l'App Store; mai no veiem les dades de la teva targeta ni bancàries.",
             "Per saber si el teu pla Pro està actiu, Pupdojo fa servir RevenueCat, un servei de subscripcions. RevenueCat rep el teu historial de compres de l'App Store juntament amb un identificador aleatori d'usuari de l'app que no està vinculat al teu nom ni al teu correu. És l'única dada que surt del teu dispositiu, i només s'utilitza per desbloquejar el que has pagat i restaurar-ho als teus altres dispositius."]),
        sec("thirdPartyServices", ("Service providers", "Proveedores de servicios", "Proveïdors de serveis"),
            ["Pupdojo relies on Apple (App Store, StoreKit, iCloud and notifications) and RevenueCat (subscription status). Each processes information under its own privacy policy and only to provide its service. We do not use advertising, analytics or data broker services."],
            ["Pupdojo se apoya en Apple (App Store, StoreKit, iCloud y notificaciones) y RevenueCat (estado de la suscripción). Cada uno trata la información según su propia política de privacidad y solo para prestar su servicio. No usamos servicios de publicidad, analítica ni intermediarios de datos."],
            ["Pupdojo es recolza en Apple (App Store, StoreKit, iCloud i notificacions) i RevenueCat (estat de la subscripció). Cadascun tracta la informació segons la seva pròpia política de privacitat i només per prestar el seu servei. No fem servir serveis de publicitat, analítica ni intermediaris de dades."]),
        sec("dataRetention", ("Data retention", "Conservación de datos", "Conservació de dades"),
            ["Your training data stays on your device and in your iCloud for as long as you keep it. Deleting a dog in the app removes its data, and deleting the app removes everything stored on that device. RevenueCat keeps subscription records for as long as needed to provide the service and meet legal obligations."],
            ["Tus datos de adiestramiento se quedan en tu dispositivo y en tu iCloud mientras los conserves. Eliminar un perro en la app borra sus datos, y eliminar la app borra todo lo guardado en ese dispositivo. RevenueCat conserva los registros de suscripción el tiempo necesario para prestar el servicio y cumplir obligaciones legales."],
            ["Les teves dades d'ensinistrament es queden al teu dispositiu i al teu iCloud mentre les conservis. Eliminar un gos a l'app esborra les seves dades, i eliminar l'app esborra tot el que hi ha desat en aquell dispositiu. RevenueCat conserva els registres de subscripció el temps necessari per prestar el servei i complir obligacions legals."]),
        sec("security", ("Security", "Seguridad", "Seguretat"),
            ["Data on your device is protected by iOS data protection, and iCloud data is protected by Apple's security. Because we do not run servers that hold your training data, there is no Pupdojo database that could be breached."],
            ["Los datos de tu dispositivo están protegidos por la protección de datos de iOS, y los de iCloud por la seguridad de Apple. Como no tenemos servidores con tus datos de adiestramiento, no existe ninguna base de datos de Pupdojo que pueda sufrir una brecha."],
            ["Les dades del teu dispositiu estan protegides per la protecció de dades d'iOS, i les de l'iCloud per la seguretat d'Apple. Com que no tenim servidors amb les teves dades d'ensinistrament, no existeix cap base de dades de Pupdojo que pugui patir una bretxa."]),
        sec("userRights", ("Your rights", "Tus derechos", "Els teus drets"),
            ["You control your data directly in the app: you can edit or delete any dog, photo, log or journal entry at any time. Depending on where you live, including the European Economic Area, the United Kingdom and California, you may also have rights to access, correct, delete or port information and to object to processing. For anything we hold through our subscription provider, see our Data Deletion page or contact " + PRIVACY + "."],
            ["Controlas tus datos directamente en la app: puedes editar o borrar cualquier perro, foto, registro o entrada de diario cuando quieras. Según dónde vivas, incluidos el Espacio Económico Europeo, el Reino Unido y California, también puedes tener derecho a acceder, rectificar, suprimir o portar información y a oponerte a su tratamiento. Para lo que conservemos a través de nuestro proveedor de suscripciones, consulta la página de Eliminación de datos o escribe a " + PRIVACY + "."],
            ["Controles les teves dades directament a l'app: pots editar o esborrar qualsevol gos, foto, registre o entrada de diari quan vulguis. Segons on visquis, inclosos l'Espai Econòmic Europeu, el Regne Unit i Califòrnia, també pots tenir dret a accedir, rectificar, suprimir o portar informació i a oposar-te al seu tractament. Per al que conservem a través del nostre proveïdor de subscripcions, consulta la pàgina d'Eliminació de dades o escriu a " + PRIVACY + "."]),
        sec("childrensPrivacy", ("Children's privacy", "Privacidad de los menores", "Privacitat dels menors"),
            ["Pupdojo is a training app for dog owners and is not directed at children. We do not knowingly collect personal information from children."],
            ["Pupdojo es una app de adiestramiento para personas con perro y no está dirigida a menores. No recogemos a sabiendas información personal de menores."],
            ["Pupdojo és una app d'ensinistrament per a persones amb gos i no està adreçada a menors. No recollim conscientment informació personal de menors."]),
        sec("changes", ("Changes to this policy", "Cambios en esta política", "Canvis en aquesta política"),
            ["If we change how Pupdojo handles information, we will update this page and the date above, and where the change is significant we will tell you in the app."],
            ["Si cambiamos cómo trata Pupdojo la información, actualizaremos esta página y la fecha de arriba, y si el cambio es importante te lo diremos en la app."],
            ["Si canviem com tracta Pupdojo la informació, actualitzarem aquesta pàgina i la data de dalt, i si el canvi és important t'ho direm a l'app."]),
        sec("contact", ("Contact", "Contacto", "Contacte"),
            ["Pupdojo is published by Idion, based in Spain. Questions about this policy: " + PRIVACY + ". Help with the app: " + SUPPORT + "."],
            ["Pupdojo la publica Idion, con sede en España. Preguntas sobre esta política: " + PRIVACY + ". Ayuda con la app: " + SUPPORT + "."],
            ["Pupdojo la publica Idion, amb seu a Espanya. Preguntes sobre aquesta política: " + PRIVACY + ". Ajuda amb l'app: " + SUPPORT + "."]),
    ])

terms = doc("terms", "terms",
    ("Pupdojo Terms of Use", "Condiciones de uso de Pupdojo", "Condicions d'ús de Pupdojo"),
    ("The licence agreement for the Pupdojo app: subscriptions, acceptable use, training content and the app store terms.",
     "El acuerdo de licencia de la app Pupdojo: suscripciones, uso aceptable, contenido de adiestramiento y condiciones de las tiendas de apps.",
     "L'acord de llicència de l'app Pupdojo: subscripcions, ús acceptable, contingut d'ensinistrament i condicions de les botigues d'apps."),
    [
        sec("licenceScope", ("Licence and scope of use", "Licencia y alcance de uso", "Llicència i abast d'ús"),
            ["These Terms of Use are the end-user licence agreement between you and Idion for the Pupdojo app. By downloading or using Pupdojo, you accept them.",
             "We grant you a personal, non-exclusive, non-transferable, revocable licence to use Pupdojo on Apple-branded devices that you own or control, subject to the Usage Rules in the Apple Media Services Terms and Conditions, including Family Sharing where it applies. You may not sell, rent, sublicense or redistribute Pupdojo, or copy, modify, decompile or reverse engineer it except where the law expressly allows."],
            ["Estas Condiciones de uso son el acuerdo de licencia de usuario final entre tú e Idion para la app Pupdojo. Al descargar o usar Pupdojo, las aceptas.",
             "Te concedemos una licencia personal, no exclusiva, intransferible y revocable para usar Pupdojo en dispositivos de Apple que tengas o controles, sujeta a las Reglas de uso de los Términos y condiciones de los Servicios multimedia de Apple, incluida En familia cuando corresponda. No puedes vender, alquilar, sublicenciar ni redistribuir Pupdojo, ni copiarla, modificarla, descompilarla o aplicarle ingeniería inversa salvo donde la ley lo permita expresamente."],
            ["Aquestes Condicions d'ús són l'acord de llicència d'usuari final entre tu i Idion per a l'app Pupdojo. En descarregar o utilitzar Pupdojo, les acceptes.",
             "Et concedim una llicència personal, no exclusiva, intransferible i revocable per utilitzar Pupdojo en dispositius d'Apple que tinguis o controlis, subjecta a les Normes d'ús dels Termes i condicions dels Serveis multimèdia d'Apple, inclosa En família quan correspongui. No pots vendre, llogar, subllicenciar ni redistribuir Pupdojo, ni copiar-la, modificar-la, descompilar-la o aplicar-hi enginyeria inversa excepte on la llei ho permeti expressament."]),
        sec("trainingContent", ("Training content and your dog's welfare", "Contenido de adiestramiento y bienestar de tu perro", "Contingut d'ensinistrament i benestar del teu gos"),
            ["Pupdojo offers general, positive-reinforcement training guidance. It is not veterinary advice and is not a substitute for a veterinarian or a certified behaviour professional. Always watch your dog's body language, stop if your dog is stressed or in pain, and talk to your vet about health, aggression, separation distress or sudden changes in behaviour.",
             "You are responsible for your dog's safety and for training in a safe place, including keeping your dog on a leash where the law or common sense requires it."],
            ["Pupdojo ofrece orientación general de adiestramiento en positivo. No es consejo veterinario ni sustituye a un veterinario o a un profesional del comportamiento certificado. Observa siempre el lenguaje corporal de tu perro, para si está estresado o le duele algo, y habla con tu veterinario sobre salud, agresividad, ansiedad por separación o cambios bruscos de conducta.",
             "Eres responsable de la seguridad de tu perro y de entrenar en un lugar seguro, incluido llevarlo con correa donde la ley o el sentido común lo exijan."],
            ["Pupdojo ofereix orientació general d'ensinistrament en positiu. No és consell veterinari ni substitueix un veterinari o un professional del comportament certificat. Observa sempre el llenguatge corporal del teu gos, atura't si està estressat o li fa mal alguna cosa, i parla amb el teu veterinari sobre salut, agressivitat, ansietat per separació o canvis bruscos de conducta.",
             "Ets responsable de la seguretat del teu gos i d'entrenar en un lloc segur, inclòs portar-lo lligat on la llei o el sentit comú ho exigeixin."]),
        sec("subscriptions", ("Subscriptions and payment", "Suscripciones y pago", "Subscripcions i pagament"),
            ["The first session, the clicker and the trackers are free. Pupdojo Pro unlocks every plan and lesson. It is sold as an auto-renewable subscription through the App Store, on the price and period shown before you confirm; the yearly plan may include a free trial.",
             "Payment is charged to your Apple Account when you confirm. The subscription renews automatically unless you cancel it at least 24 hours before the end of the current period, and any unused part of a free trial is forfeited when you buy a subscription. You can manage or cancel it in your App Store account settings. Refunds are handled by Apple under its policies."],
            ["La primera sesión, el clicker y los registros son gratis. Pupdojo Pro desbloquea todos los planes y lecciones. Se vende como suscripción de renovación automática a través del App Store, al precio y periodo que se muestran antes de confirmar; el plan anual puede incluir una prueba gratuita.",
             "El pago se carga en tu cuenta de Apple al confirmar. La suscripción se renueva automáticamente salvo que la canceles al menos 24 horas antes del final del periodo, y la parte no usada de una prueba gratuita se pierde al comprar una suscripción. Puedes gestionarla o cancelarla en los ajustes de tu cuenta del App Store. Los reembolsos los gestiona Apple según sus políticas."],
            ["La primera sessió, el clicker i els registres són gratis. Pupdojo Pro desbloqueja tots els plans i lliçons. Es ven com a subscripció de renovació automàtica a través de l'App Store, al preu i període que es mostren abans de confirmar; el pla anual pot incloure una prova gratuïta.",
             "El pagament es carrega al teu compte d'Apple en confirmar. La subscripció es renova automàticament si no la cancel·les com a mínim 24 hores abans del final del període, i la part no utilitzada d'una prova gratuïta es perd en comprar una subscripció. Pots gestionar-la o cancel·lar-la a la configuració del teu compte de l'App Store. Els reemborsaments els gestiona Apple segons les seves polítiques."]),
        sec("yourContent", ("Your content", "Tu contenido", "El teu contingut"),
            ["Photos, notes and logs you add stay yours and stay on your device and in your iCloud. You are responsible for having the right to use any photo you add."],
            ["Las fotos, notas y registros que añades siguen siendo tuyos y se quedan en tu dispositivo y en tu iCloud. Eres responsable de tener derecho a usar cualquier foto que añadas."],
            ["Les fotos, notes i registres que afegeixes continuen sent teus i es queden al teu dispositiu i al teu iCloud. Ets responsable de tenir dret a utilitzar qualsevol foto que afegeixis."]),
        sec("intellectualProperty", ("Intellectual property", "Propiedad intelectual", "Propietat intel·lectual"),
            ["Pupdojo, including its software, lessons, the Mochi character, design and branding, belongs to Idion or its licensors. If a third party claims that Pupdojo infringes their intellectual property, Idion, not Apple, is responsible for investigating, defending, settling and discharging that claim."],
            ["Pupdojo, incluidos su software, lecciones, el personaje Mochi, diseño y marca, pertenece a Idion o a sus licenciantes. Si un tercero alega que Pupdojo infringe su propiedad intelectual, Idion, y no Apple, es responsable de investigar, defender, resolver y liquidar esa reclamación."],
            ["Pupdojo, inclosos el seu programari, lliçons, el personatge Mochi, disseny i marca, pertany a Idion o als seus llicenciants. Si un tercer al·lega que Pupdojo infringeix la seva propietat intel·lectual, Idion, i no Apple, és responsable d'investigar, defensar, resoldre i liquidar aquesta reclamació."]),
        sec("disclaimers", ("Disclaimers and liability", "Exención de garantías y responsabilidad", "Exempció de garanties i responsabilitat"),
            ["Pupdojo is provided \"as is\". Every dog learns differently, and we do not guarantee any particular training result. To the maximum extent permitted by law, Idion is not liable for indirect, incidental or consequential damages arising from your use of Pupdojo. Nothing in these terms limits rights you have as a consumer under mandatory law."],
            ["Pupdojo se ofrece \"tal cual\". Cada perro aprende de forma distinta y no garantizamos ningún resultado concreto. En la máxima medida permitida por la ley, Idion no responde de daños indirectos, incidentales o consecuentes derivados del uso de Pupdojo. Nada de estas condiciones limita los derechos que tengas como consumidor según la ley imperativa."],
            ["Pupdojo s'ofereix \"tal com és\". Cada gos aprèn de manera diferent i no garantim cap resultat concret. En la màxima mesura permesa per la llei, Idion no respon de danys indirectes, incidentals o conseqüents derivats de l'ús de Pupdojo. Res d'aquestes condicions limita els drets que tinguis com a consumidor segons la llei imperativa."]),
        sec("appStoreTerms", ("App store terms", "Condiciones del App Store", "Condicions de l'App Store"),
            ["These terms are between you and Idion only, not Apple, and Apple is not responsible for Pupdojo or its content. Apple has no obligation to provide maintenance or support for Pupdojo. If Pupdojo fails to conform to any applicable warranty, you may notify Apple, and Apple may refund the purchase price, if any; Apple has no other warranty obligation.",
             "Apple is not responsible for any claims relating to Pupdojo, including product liability claims, claims that it fails to meet legal or regulatory requirements, or consumer protection claims. Apple and its subsidiaries are third-party beneficiaries of these terms and may enforce them against you.",
             "You confirm that you are not located in a country subject to a U.S. Government embargo or designated as a \"terrorist supporting\" country, and that you are not on any U.S. Government list of prohibited or restricted parties. You must also comply with applicable third-party terms, such as your wireless data plan."],
            ["Estas condiciones son solo entre tú e Idion, no con Apple, y Apple no es responsable de Pupdojo ni de su contenido. Apple no tiene obligación de prestar mantenimiento ni soporte para Pupdojo. Si Pupdojo no cumple alguna garantía aplicable, puedes notificarlo a Apple, que podrá reembolsar el precio de compra, si lo hubo; Apple no tiene ninguna otra obligación de garantía.",
             "Apple no es responsable de ninguna reclamación relacionada con Pupdojo, incluidas reclamaciones por responsabilidad de producto, por incumplir requisitos legales o normativos o de protección del consumidor. Apple y sus filiales son terceros beneficiarios de estas condiciones y pueden exigirte su cumplimiento.",
             "Confirmas que no te encuentras en un país sujeto a embargo del Gobierno de EE. UU. o designado como país que \"apoya el terrorismo\", y que no figuras en ninguna lista del Gobierno de EE. UU. de partes prohibidas o restringidas. También debes cumplir las condiciones de terceros aplicables, como tu plan de datos móviles."],
            ["Aquestes condicions són només entre tu i Idion, no amb Apple, i Apple no és responsable de Pupdojo ni del seu contingut. Apple no té l'obligació de prestar manteniment ni suport per a Pupdojo. Si Pupdojo no compleix alguna garantia aplicable, pots notificar-ho a Apple, que podrà reemborsar el preu de compra, si n'hi va haver; Apple no té cap altra obligació de garantia.",
             "Apple no és responsable de cap reclamació relacionada amb Pupdojo, incloses reclamacions per responsabilitat de producte, per incomplir requisits legals o normatius o de protecció del consumidor. Apple i les seves filials són tercers beneficiaris d'aquestes condicions i te'n poden exigir el compliment.",
             "Confirmes que no et trobes en un país subjecte a embargament del Govern dels EUA o designat com a país que \"dona suport al terrorisme\", i que no figures en cap llista del Govern dels EUA de parts prohibides o restringides. També has de complir les condicions de tercers aplicables, com el teu pla de dades mòbils."]),
        sec("termination", ("Termination and changes", "Terminación y cambios", "Finalització i canvis"),
            ["You can stop using Pupdojo at any time by deleting the app and cancelling any subscription. We may update Pupdojo and these terms; material changes will be shown in the app or on this page before they apply."],
            ["Puedes dejar de usar Pupdojo cuando quieras borrando la app y cancelando cualquier suscripción. Podemos actualizar Pupdojo y estas condiciones; los cambios importantes se mostrarán en la app o en esta página antes de aplicarse."],
            ["Pots deixar d'utilitzar Pupdojo quan vulguis esborrant l'app i cancel·lant qualsevol subscripció. Podem actualitzar Pupdojo i aquestes condicions; els canvis importants es mostraran a l'app o en aquesta pàgina abans d'aplicar-se."]),
        sec("governingLaw", ("Governing law", "Ley aplicable", "Llei aplicable"),
            ["These terms are governed by the laws of Spain. If you are a consumer resident in the European Union, you keep the protection of the mandatory laws of your country and may bring proceedings before its courts."],
            ["Estas condiciones se rigen por las leyes de España. Si eres consumidor residente en la Unión Europea, conservas la protección de las leyes imperativas de tu país y puedes acudir a sus tribunales."],
            ["Aquestes condicions es regeixen per les lleis d'Espanya. Si ets consumidor resident a la Unió Europea, conserves la protecció de les lleis imperatives del teu país i pots acudir als seus tribunals."]),
        sec("whoWeAre", ("Who we are and how to reach us", "Quiénes somos y cómo contactarnos", "Qui som i com contactar-nos"),
            ["Pupdojo is published by Idion, based in Spain. For help with the app, contact " + SUPPORT + ". For questions about these terms, contact " + LEGAL + "."],
            ["Pupdojo la publica Idion, con sede en España. Para ayuda con la app, escribe a " + SUPPORT + ". Para preguntas sobre estas condiciones, escribe a " + LEGAL + "."],
            ["Pupdojo la publica Idion, amb seu a Espanya. Per a ajuda amb l'app, escriu a " + SUPPORT + ". Per a preguntes sobre aquestes condicions, escriu a " + LEGAL + "."]),
    ], label="termsEula")

contact = doc("contact", "contact",
    ("Contact Pupdojo", "Contacto de Pupdojo", "Contacte de Pupdojo"),
    ("How to get help with Pupdojo, manage your subscription or reach the team behind it.",
     "Cómo conseguir ayuda con Pupdojo, gestionar tu suscripción o contactar con el equipo.",
     "Com aconseguir ajuda amb Pupdojo, gestionar la teva subscripció o contactar amb l'equip."),
    [
        sec("support", ("App support", "Soporte de la app", "Suport de l'app"),
            ["For help using Pupdojo, contact " + SUPPORT + ". Tell us your device, iOS version and what happened, and we will get back to you."],
            ["Para ayuda con Pupdojo, escribe a " + SUPPORT + ". Indícanos tu dispositivo, la versión de iOS y qué ha pasado, y te responderemos."],
            ["Per a ajuda amb Pupdojo, escriu a " + SUPPORT + ". Indica'ns el teu dispositiu, la versió d'iOS i què ha passat, i et respondrem."]),
        sec("subscriptions", ("Subscriptions and refunds", "Suscripciones y reembolsos", "Subscripcions i reemborsaments"),
            ["Pupdojo Pro is billed by Apple. To cancel or change it, open Settings on your iPhone or iPad, tap your name, then Subscriptions. To ask for a refund, visit reportaproblem.apple.com. To restore a purchase on a new device, open Pupdojo and tap Restore purchases on the subscription screen."],
            ["Pupdojo Pro lo cobra Apple. Para cancelarla o cambiarla, abre Ajustes en tu iPhone o iPad, toca tu nombre y luego Suscripciones. Para pedir un reembolso, visita reportaproblem.apple.com. Para restaurar una compra en un dispositivo nuevo, abre Pupdojo y toca Restaurar compras en la pantalla de suscripción."],
            ["Pupdojo Pro la cobra Apple. Per cancel·lar-la o canviar-la, obre Configuració al teu iPhone o iPad, toca el teu nom i després Subscripcions. Per demanar un reemborsament, visita reportaproblem.apple.com. Per restaurar una compra en un dispositiu nou, obre Pupdojo i toca Restaurar compres a la pantalla de subscripció."]),
        sec("privacy", ("Privacy requests", "Solicitudes de privacidad", "Sol·licituds de privacitat"),
            ["To exercise your rights under our Privacy Policy, or to request data deletion, contact " + PRIVACY + "."],
            ["Para ejercer tus derechos según nuestra Política de privacidad, o pedir la eliminación de datos, escribe a " + PRIVACY + "."],
            ["Per exercir els teus drets segons la nostra Política de privacitat, o demanar l'eliminació de dades, escriu a " + PRIVACY + "."]),
        sec("security", ("Security disclosures", "Avisos de seguridad", "Avisos de seguretat"),
            ["If you have found a security vulnerability in Pupdojo, please report it to " + SECURITY + " rather than disclosing it publicly."],
            ["Si has encontrado una vulnerabilidad de seguridad en Pupdojo, comunícala a " + SECURITY + " en lugar de hacerla pública."],
            ["Si has trobat una vulnerabilitat de seguretat a Pupdojo, comunica-la a " + SECURITY + " en lloc de fer-la pública."]),
        sec("legal", ("Legal", "Legal", "Legal"),
            ["For legal enquiries related to Pupdojo, contact " + LEGAL + "."],
            ["Para consultas legales relacionadas con Pupdojo, escribe a " + LEGAL + "."],
            ["Per a consultes legals relacionades amb Pupdojo, escriu a " + LEGAL + "."]),
        sec("responseTime", ("Response time and languages", "Tiempo de respuesta e idiomas", "Temps de resposta i idiomes"),
            ["We aim to reply within a few business days, in English, Spanish or Catalan. Privacy and security requests are prioritised."],
            ["Intentamos responder en pocos días laborables, en inglés, español o catalán. Las solicitudes de privacidad y seguridad tienen prioridad."],
            ["Intentem respondre en pocs dies laborables, en anglès, castellà o català. Les sol·licituds de privacitat i seguretat tenen prioritat."]),
    ])

deletion = doc("dataDeletion", "data-deletion",
    ("Delete your Pupdojo data", "Eliminar tus datos de Pupdojo", "Eliminar les teves dades de Pupdojo"),
    ("How to delete your dogs, photos and progress from Pupdojo, your iCloud and our subscription provider.",
     "Cómo borrar tus perros, fotos y progreso de Pupdojo, de tu iCloud y de nuestro proveedor de suscripciones.",
     "Com esborrar els teus gossos, fotos i progrés de Pupdojo, del teu iCloud i del nostre proveïdor de subscripcions."),
    [
        sec("inApp", ("Delete in the app", "Borrar desde la app", "Esborrar des de l'app"),
            ["Pupdojo has no account, so there is nothing to close. To delete a dog and all of its plans, photos, logs and journal entries, open Profile, choose the dog, tap Edit profile and then Delete. To delete everything on a device, delete the app."],
            ["Pupdojo no tiene cuenta, así que no hay nada que cerrar. Para borrar un perro y todos sus planes, fotos, registros y entradas de diario, abre Perfil, elige el perro, toca Editar perfil y después Eliminar. Para borrarlo todo de un dispositivo, elimina la app."],
            ["Pupdojo no té compte, així que no hi ha res a tancar. Per esborrar un gos i tots els seus plans, fotos, registres i entrades de diari, obre Perfil, tria el gos, toca Editar perfil i després Eliminar. Per esborrar-ho tot d'un dispositiu, elimina l'app."]),
        sec("iCloud", ("Delete your iCloud copy", "Borrar la copia de iCloud", "Esborrar la còpia de l'iCloud"),
            ["If iCloud sync was on, deleting a dog in the app also removes it from your iCloud. To remove all Pupdojo data from iCloud, open Settings, tap your name, then iCloud, Manage Account Storage (or Manage Storage), choose Pupdojo and delete its data."],
            ["Si la sincronización con iCloud estaba activada, borrar un perro en la app también lo elimina de tu iCloud. Para quitar todos los datos de Pupdojo de iCloud, abre Ajustes, toca tu nombre, luego iCloud, Gestionar almacenamiento, elige Pupdojo y elimina sus datos."],
            ["Si la sincronització amb l'iCloud estava activada, esborrar un gos a l'app també l'elimina del teu iCloud. Per treure totes les dades de Pupdojo de l'iCloud, obre Configuració, toca el teu nom, després iCloud, Gestionar l'emmagatzematge, tria Pupdojo i elimina'n les dades."]),
        sec("subscriptionRecords", ("Subscription records", "Registros de suscripción", "Registres de subscripció"),
            ["Our subscription provider holds your App Store purchase history under a random identifier. To have it deleted, email " + PRIVACY + " with the subject \"Pupdojo data deletion\" and the Apple order ID from your purchase receipt, so we can find the record without knowing who you are."],
            ["Nuestro proveedor de suscripciones guarda tu historial de compras del App Store bajo un identificador aleatorio. Para que lo borremos, escribe a " + PRIVACY + " con el asunto \"Eliminación de datos de Pupdojo\" y el ID de pedido de Apple de tu recibo, para que podamos encontrar el registro sin saber quién eres."],
            ["El nostre proveïdor de subscripcions desa el teu historial de compres de l'App Store sota un identificador aleatori. Perquè l'esborrem, escriu a " + PRIVACY + " amb l'assumpte \"Eliminació de dades de Pupdojo\" i l'ID de comanda d'Apple del teu rebut, perquè puguem trobar el registre sense saber qui ets."]),
        sec("whatMayBeRetained", ("What may be retained", "Qué puede conservarse", "Què es pot conservar"),
            ["Apple keeps its own purchase records under its policies. We may keep minimal subscription records where the law requires it, for no longer than that obligation lasts, and for no other purpose."],
            ["Apple conserva sus propios registros de compra según sus políticas. Podemos conservar registros mínimos de suscripción cuando la ley lo exija, no más tiempo del que dure esa obligación y para ningún otro fin."],
            ["Apple conserva els seus propis registres de compra segons les seves polítiques. Podem conservar registres mínims de subscripció quan la llei ho exigeixi, no més temps del que duri aquesta obligació i per a cap altra finalitat."]),
        sec("responseProcess", ("Response time", "Plazo de respuesta", "Termini de resposta"),
            ["We process verified deletion requests within 30 days."],
            ["Tramitamos las solicitudes de eliminación verificadas en un plazo de 30 días."],
            ["Tramitem les sol·licituds d'eliminació verificades en un termini de 30 dies."]),
    ])

payload = {"runId": "2026-W40-pupdojo", "slug": "pupdojo", "supportEmail": SUPPORT,
           "legal": {"documents": [privacy, terms, contact, deletion]}}
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pupdojo-legal.json")
json.dump(payload, open(out, "w"), ensure_ascii=False, indent=1)
print("wrote", out)
